### ISSUE TITLE
Replacing Close with Dispose

### ISSUE THREAD

**Issue by Uzi-Granot** [StefH/UZipDotNet#1]
According to the Microsoft documentation the Close method calls the Dispose method. The question is what is the point of making this substitution?

**Comment by StefH** [comment]
In ASPNET5 and ASPNETCORE5, the method Close has been replaced by Dispose.

Actually Microsoft describes this in the reference source comment:

``` c#
// Stream used to require that all cleanup logic went into Close(),
// which was thought up before we invented IDisposable.  However, we 
// need to follow the IDisposable pattern so that users can write
// sensible subclasses without needing to inspect all their base 
// classes, and without worrying about version brittleness, from a 
// base class switching to the Dispose pattern.  We're moving
// Stream to the Dispose(bool) pattern - that's where all subclasses 
// should put their cleanup starting in V2.
public virtual void Close()
```

**Comment by Uzi-Granot** [comment]
Hi Stef,

This is very interesting. The remark in the dispose method documentation is:

“Note that because of backward compatibility requirements, this method's implementation differs from the recommended guidance for the Dispose pattern.  This method calls Close, which then calls Stream.Dispose(Boolean).”

So now you call dispose that calls close that calls dispose. 

I am fully aware that this stupidity is not yours. I just sometimes wander about Microsoft logic.

In any case, it is all a waste of time. This change will not make the software any better just a little slower.

Thanks for posting it on Github and good luck with your project.

Uzi
